---
# Django Messaging App Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django-messaging-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: v1
    spec:
      containers:
      - name: django-app
        image: your-username/django-messaging-app:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          value: "False"
        - name: DJANGO_SETTINGS_MODULE
          value: "messaging_app.settings"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: ALLOWED_HOSTS
          value: "localhost,127.0.0.1,django-messaging-app-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
---
# Service to expose the Django app internally
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app-service
  labels:
    app: django-messaging-app
spec:
  type: ClusterIP
  selector:
    app: django-messaging-app
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
---
# ConfigMap for Django settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  settings.py: |
    # Django production settings
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "django-messaging-app-service"]
    DEBUG = False
    CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]
---
# Secret for sensitive data (you should replace these with actual values)
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # Generate with: echo -n "your-secret-key-here" | base64
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=
  # Generate with: echo -n "postgresql://user:pass@host:5432/dbname" | base64
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bob3N0OjU0MzIvZGJuYW1l
---
# Optional: Persistent Volume for static files (if needed)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-staticfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi